# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-statusline" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "76a5c16906d9b8921fb5c188ee8fee708a89d7d09cccd66a16e1bf74886cbf4a"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7a3ac367dbbc811ee862ee17fb2cb1e7b78dfa24a777f9bc15467f934a3e128"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "27ac77c3cffc90d746c366ea41a1acf61db01d8cb680e97f6af5921162ae40d7"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba8017633dfd7a7501796cdda24cd79e67ea390e8d126b50b8b6b3e44ded6c42"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-statusline"
  desc "Statusline for Claude Code terminal integration"
  homepage "https://github.com/h2ik/claude-statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-statusline"

  preflight do
    system_command "/usr/bin/xattr", args: ["-cr", "#{staged_path}/claude-statusline"]
  end

  # No zap stanza required

end
