# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-statusline" do
  version "1.3.4"

  on_macos do
    on_intel do
      sha256 "2a9f0e312d0d16d5606508d1607af4ccb60c83479a1565baaed868e10c28559f"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "523f901a89f9345cde4b8311ffad11f5a9c308fea075545b87abfffe619dd82a"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26bdd47bc9ff73925b2d13ac2a3caa7ac2da6cf4e825704692618ebac0c838b8"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "971fca6c9b256829d95fa7019c6837184805f7bdaddaabd6dccf99ceac638813"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-statusline"
  desc "Statusline for Claude Code terminal integration"
  homepage "https://github.com/h2ik/claude-statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-statusline"

  preflight do
    system_command "/usr/bin/xattr", args: ["-cr", "#{staged_path}/claude-statusline"]
  end

  # No zap stanza required

end
