# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-statusline" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "30c6bdc5966e66f83166bb9fbfc5b05da876790507d5a2b1a1f7bbbe75f659cb"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b7dd80c0eb6d14b96d8e0c1ee868d586b19f7451fa981b2e99fa0799867f2cf9"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8624baec8497e91c8572b69efeef982c0f561f90b67ec4760db0ada2e489b33e"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d1eef1e021492bf45f70a3baef4917b9fe4012987c4a6f4d0bd03b52d593bee"
      url "https://github.com/h2ik/claude-statusline/releases/download/v#{version}/claude-statusline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-statusline"
  desc "Statusline for Claude Code terminal integration"
  homepage "https://github.com/h2ik/claude-statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-statusline"

  preflight do
    system_command "/usr/bin/xattr", args: ["-cr", "#{staged_path}/claude-statusline"]
  end

  # No zap stanza required

end
